### ISSUE TITLE
Iteratee path

### ISSUE THREAD

**Issue by srph** [steadicat/mutatis#1]
Hi there, thanks to yous library!

I'd like to suggest something bit similar to [_.iteratee](https://lodash.com/docs/4.17.4#iteratee). This way, we can `update` something other than through key path; useful if you want to update something by id or name.

```js
var tasks = mutatis(this.state.tasks)
  .update(task => (task.id === id), (task) => ({
    ...task,
    checked: !task.checked
  }))
  .values();
```

Even further,
```js
var tasks = mutatis(this.state.tasks)
  .update({ id: id }, (task) => ({
    ...task,
    checked: !task.checked
  }))
  .values();
```

I think this would make the key-pathing even more complex if we tried something like:

```
['a', 'b', 'c', { id: id }]
```

Though, we can avoid it though by not implemeting iteratee to the keypathing.

I'd like to send a PR if that's not much too much to ask. Feel free to close! 😄

**Comment by srph** [comment]
I realized this feature would complicate things.

I think a simpler workaround would be:

```js
const index = this.state.tasks
  .findIndex((task) => task.id === id);

const tasks = mutatis(this.state.tasks)
  .update(index, (task) => ({
    ...task,
    checked: !task.checked
  }))
  .values();
```

**Comment by steadicat** [comment]
Yeah I like your workaround.

Remember that you can use a path key to only update the part of the object that's changing. So your last example can be simplified to:

```javascript
const index = this.state.tasks
  .findIndex((task) => task.id === id);

const tasks = mutatis(this.state.tasks)
  .updateIn([index, 'checked'], (checked) => !checked);
```

An alternative solution is to use map:
```javascript
const tasks = mutatis(this.state.tasks)
  .map((task) =>
    task.id === id ?
      task.update('checked', (checked) => !checked) :
      task)
```
